// <auto-generated />
using System;
using AppEmpresa.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppEmpresa.Migrations
{
    [DbContext(typeof(ProductContext))]
    partial class ProductContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppEmpresa.Models.Product", b =>
                {
                    b.Property<int>("productId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("productId"));

                    b.Property<string>("productDateIn")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("productDateOut")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("productDescription")
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool?>("productIsFaulty")
                        .HasColumnType("bit");

                    b.Property<string>("productName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("productPrice")
                        .HasColumnType("int");

                    b.Property<int?>("productQuantity")
                        .HasColumnType("int");

                    b.HasKey("productId");

                    b.ToTable("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
